---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pttg-fs-service
  name: pttg-fs-service
spec:
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
    targetPort: https
  selector:
    name: pttg-fs-service